public class create_accoutn_record {
    public void demo(){
        Account acc =new Account();
        acc.Name='amit kumar';
        acc.Phone='0989988998';
        system.debug('acc =>' + acc);
    }
        public void demo1(){
            EMPLOYEE__c emp = new EMPLOYEE__c();
            emp.Address__c = 'birounnnn';
            emp.Is_Active__c = true;
            system.debug('emp =>' + emp);
     
        }   
    
    

    
    
    
}